// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXYU0adsiGZuuMfZsFKi3nN2aqH8lFUpo',
    appId: '1:748404964606:web:c3c1a49a863996ee9539af',
    messagingSenderId: '748404964606',
    projectId: 'testdemowilsonwings',
    authDomain: 'testdemowilsonwings.firebaseapp.com',
    storageBucket: 'testdemowilsonwings.appspot.com',
    measurementId: 'G-BB42LEQ512',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1x_hR5FiE-QddMMP40atMU1dNgOhJmB0',
    appId: '1:748404964606:android:0341fe9cbd4de4a29539af',
    messagingSenderId: '748404964606',
    projectId: 'testdemowilsonwings',
    storageBucket: 'testdemowilsonwings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEDbO4Bsmgz9Y_frP0GrZt3JLW-FoBVHI',
    appId: '1:748404964606:ios:88ea62c458ab71ad9539af',
    messagingSenderId: '748404964606',
    projectId: 'testdemowilsonwings',
    storageBucket: 'testdemowilsonwings.appspot.com',
    iosClientId: '748404964606-i09pu7lujn9v1bmf7nomno3tmafdp01h.apps.googleusercontent.com',
    iosBundleId: 'com.example.testdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEDbO4Bsmgz9Y_frP0GrZt3JLW-FoBVHI',
    appId: '1:748404964606:ios:b79073bd52f328ed9539af',
    messagingSenderId: '748404964606',
    projectId: 'testdemowilsonwings',
    storageBucket: 'testdemowilsonwings.appspot.com',
    iosClientId: '748404964606-ds318mjmdgonj7utqf02cjnquls4ogai.apps.googleusercontent.com',
    iosBundleId: 'com.example.testdemo.RunnerTests',
  );
}
